import { CircuitType } from '@/lib/simulation-store'

function shiftRegister(n: number): string {
  return `// ${n}-bit SIPO Shift Register
// Generated by Virtual Sequential Logic Simulator

module shift_register_${n}bit (
  input  wire clk,
  input  wire rst,
  input  wire d_in,
  output wire [${n - 1}:0] q
);
  reg [${n - 1}:0] shift_reg;

  always @(posedge clk or posedge rst) begin
    if (rst)
      shift_reg <= ${n}'b0;
    else
      shift_reg <= {shift_reg[${n - 2}:0], d_in};
  end

  assign q = shift_reg;

endmodule
`
}

function ringCounter(n: number): string {
  return `// ${n}-bit Ring Counter
// Generated by Virtual Sequential Logic Simulator

module ring_counter_${n}bit (
  input  wire clk,
  input  wire rst,
  output wire [${n - 1}:0] q
);
  reg [${n - 1}:0] ring_reg;

  always @(posedge clk or posedge rst) begin
    if (rst)
      ring_reg <= ${n}'b${'1' + '0'.repeat(n - 1)};
    else
      ring_reg <= {ring_reg[0], ring_reg[${n - 1}:1]};
  end

  assign q = ring_reg;

endmodule
`
}

function johnsonCounter(n: number): string {
  return `// ${n}-bit Johnson Counter (Twisted Ring Counter)
// Generated by Virtual Sequential Logic Simulator

module johnson_counter_${n}bit (
  input  wire clk,
  input  wire rst,
  output wire [${n - 1}:0] q
);
  reg [${n - 1}:0] johnson_reg;

  always @(posedge clk or posedge rst) begin
    if (rst)
      johnson_reg <= ${n}'b0;
    else
      johnson_reg <= {~johnson_reg[0], johnson_reg[${n - 1}:1]};
  end

  assign q = johnson_reg;

endmodule
`
}

function dFlipFlop(): string {
  return `// D Flip-Flop
// Generated by Virtual Sequential Logic Simulator

module d_flip_flop (
  input  wire clk,
  input  wire rst,
  input  wire d,
  output reg  q,
  output wire q_bar
);
  always @(posedge clk or posedge rst) begin
    if (rst) q <= 1'b0;
    else     q <= d;
  end

  assign q_bar = ~q;

endmodule
`
}

function jkFlipFlop(): string {
  return `// JK Flip-Flop
// Generated by Virtual Sequential Logic Simulator

module jk_flip_flop (
  input  wire clk,
  input  wire rst,
  input  wire j,
  input  wire k,
  output reg  q,
  output wire q_bar
);
  always @(posedge clk or posedge rst) begin
    if (rst)         q <= 1'b0;
    else if (j & ~k) q <= 1'b1;
    else if (~j & k) q <= 1'b0;
    else if (j & k)  q <= ~q;
  end

  assign q_bar = ~q;

endmodule
`
}

function tFlipFlop(): string {
  return `// T Flip-Flop (Toggle)
// Generated by Virtual Sequential Logic Simulator

module t_flip_flop (
  input  wire clk,
  input  wire rst,
  input  wire t,
  output reg  q,
  output wire q_bar
);
  always @(posedge clk or posedge rst) begin
    if (rst) q <= 1'b0;
    else if (t) q <= ~q;
  end

  assign q_bar = ~q;

endmodule
`
}

export function generateVerilog(circuitType: CircuitType, numFlipFlops: number): string {
  switch (circuitType) {
    case 'Shift Register':   return shiftRegister(numFlipFlops)
    case 'Ring Counter':     return ringCounter(numFlipFlops)
    case 'Johnson Counter':  return johnsonCounter(numFlipFlops)
    case 'D Flip-Flop':      return dFlipFlop()
    case 'JK Flip-Flop':     return jkFlipFlop()
    case 'T Flip-Flop':      return tFlipFlop()
    default:                 return shiftRegister(numFlipFlops)
  }
}

export function downloadVerilog(code: string, filename: string) {
  const blob = new Blob([code], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
